version: "3"

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file: stack.env

  mattermost:
    depends_on:
      - postgres
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    ports:
      - 8065:8065
      - 8066:8443/udp
    tmpfs:
      - /tmp
    volumes:
      - config:/mattermost/config:rw
      - app_data:/mattermost/data:rw
      - logs:/mattermost/logs:rw
      - plugins:/mattermost/plugins:rw
      - client_plugins:/mattermost/client/plugins:rw
      - bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - TZ
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_BLEVESETTINGS_INDEXDIR
      - MM_SERVICESETTINGS_SITEURL
    env_file: stack.env

volumes:
  config:
  db_data:
  app_data:
  logs:
  plugins:
  client_plugins:
  bleve-indexes:
  
